name: Main Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:

    - name: Checkout Meadow.Foundation.Grove
      uses: actions/checkout@v3
      with:
        path: Meadow.Foundation.Grove
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          7.0.x
    
    - name: Build Meadow.Foundation.Grove
      run: dotnet build -c Release Meadow.Foundation.Grove/Source/Grove.sln
